### ISSUE TITLE
add a get_current_week() function

### ISSUE THREAD

**Issue by tanho63** [nflverse/nflreadr#104]
perhaps @guga31bb's here? 

```r
get_current_week <- function() {

  # get season
  s <- dplyr::if_else(
    lubridate::month(lubridate::today("GMT")) >= 9,
    lubridate::year(lubridate::today("GMT")) ,
    lubridate::year(lubridate::today("GMT")) - 1
  )

  # Find the first Monday of September
  day1 <- lubridate::as_date(paste(s, "09-01", sep="-"))
  week1 <- as.POSIXlt(seq(day1, length.out=7, by="day"))
  monday1 <- week1[week1$wday == 1]

  # NFL season starts 4 days later
  first_game <- (monday1 + lubridate::days(3)) %>% lubridate::as_date()

  # current week number of NFL season is 1 + how many weeks have elapsed since first game
  # (ie first game is week 1)
  current_week <- 1 +
    lubridate::days(lubridate::today("America/New_York") - first_game) %>%
    .$day %>%
    magrittr::divide_by_int(7)

  if (current_week <= 1) current_week <- 1

  return(current_week)

}
```

**Comment by tanho63** [comment]
Could actually just be simpler to go
```r

nflreadr::load_schedules() |> 
    dplyr::filter(is.na(result)) |> 
    dplyr::pull(week) |> 
    head(1)
```

**Comment by guga31bb** [comment]
> Could actually just be simpler to go
> 
> ```r
> nflreadr::load_schedules() |> 
>     dplyr::filter(is.na(result)) |> 
>     dplyr::pull(week) |> 
>     head(1)
> ```

I actually used to have it like this but it makes it more fragile if there's ever issues with the games file (eg being out of order). Going by the actual date is more reliable imo

**Comment by tanho63** [comment]
https://c.tenor.com/cHYRjCIXyckAAAAC/why-not-both-por-que-no-los-dos.gif

**Comment by tanho63** [comment]
also what do you expect this function to return in the offseason? 1 = 2022 season week or 22 = super bowl week?

**Comment by guga31bb** [comment]
Right now it should be week 22 of 2021 season. Once it ticks to 2022 then it triggers a bunch of stuff to run that doesn't actually work because the season isn't starting yet

**Comment by tanho63** [comment]
OK, have updated PR to use this logic
