### ISSUE TITLE
Should suffix replacement pattern in `clean_player_names()` replace commas?

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflreadr#108]
https://github.com/nflverse/nflreadr/blob/9e431f91787cae3ce167810706e2ac608e0670e0/R/utils_name_cleaning.R#L89

Name formats in OverTheCap data include suffixes that are preceded by a comma
``` r
nflreadr::clean_player_names("Willie Gay, Jr.")
#> [1] "Jr Willie Gay"
nflreadr::clean_player_names("Willie Gay, Jr.", convert_lastfirst = FALSE)
#> [1] "Willie Gay,"
```

**Comment by tanho63** [comment]
currently think there's no reason to need a comma at all, ideally it only has A-z (or a-z), spaces, and hyphens?

**Comment by mrcaseb** [comment]
> probably should just be gsub ` Jr\\.$| Sr\\.$| III$| II$| IV$| V$|\\'|\\.|\\,` since we don't need it to make regex capture groups - just delete those matches

I *think* this is fine. My intention was to make the modification as minor as possible because I am afraid of some weird name that will break the function. But atm I think removing commas at that stage in the function should be working

**Comment by tanho63** [comment]
also i think ' and , don't need to be escaped
