### ISSUE TITLE
Issue with load_rosters

### ISSUE THREAD

**Issue by tpenney89** [nflverse/nflreadr#111]
Rosters appear to still be reflecting roster prior to draft and NFL Free Agency. for example, Chase Edmonds and Christian Kirk still appear to be active on ARI. Looking at the load_rosters function definition for nflreadr it looks like the api was last ran on 3/10/2022? 

Screenshot should be attached

rosters_2022 <- filter(load_rosters(),position %in% c("QB","RB","WR","TE"))
view(rosters_2022)

![Screen Shot 2022-06-05 at 11 36 57 AM](https://user-images.githubusercontent.com/45411408/172058435-63a9fe4a-9760-42a9-9051-46c3d876fa37.png)

**Comment by tanho63** [comment]
Looks like the action is running but not saving to the release properly :( https://github.com/nflverse/nflfastR-roster/blob/master/src/update_roster.R

I should have time to fix this when I'm bored at work next

**Comment by tanho63** [comment]
Resolved in nflverse/nflfastR-roster@8d778d4c63f0f99ac3fa8dc40c68b8b9549a95c5
