### ISSUE TITLE
load_snap_counts has 2013 hardcoded as the earliest season, despite data for 2012 existing in the repository.

### ISSUE THREAD

**Issue by shirondru** [nflverse/nflreadr#128]
In `load_snap_counts`, the year 2013 is hard coded as the earliest season for which snap count data is available, despite snap count data existing for the year 202 in https://github.com/nflverse/nflverse-data/releases.

Here is where the year 2013 is hard coded:
`if(isTRUE(seasons)) seasons <- 2013:most_recent_season()`
`stopifnot(is.numeric(seasons),
            seasons >= 2013,
            seasons <= most_recent_season())`

I believe changing 2013 to 2012 will resolve the issue and allow 2012 data to be retrieved using load_snap_counts

**Comment by tanho63** [comment]
Good catch, would you like to make a PR for this?

**Comment by shirondru** [comment]
Done!

**Comment by tanho63** [comment]
Thanks! I’ll merge it when I’m back to a PC
