### ISSUE TITLE
load_rosters creates tibbles with different columns for different seasons, preventing mulitple years from being retrieved at once.

### ISSUE THREAD

**Issue by shirondru** [nflverse/nflreadr#129]
If I attempt to load multiple seasons of player rosters using `load_rosters` I get the following error:

`> nfl_rosters <- load_rosters(seasons=c(1999:2021))`

> Error in data.table::rbindlist(out, use.names = TRUE) : 
>   Item 4 has 30 columns, inconsistent with item 1 which has 24 columns. To fill missing columns use fill=TRUE.

This is because different seasons have different columns present in the output from load_rosters. For example, some earlier seasons are missing the column `sleeper_id` and other id columns, while later seasons do have these columns available. I believe this can be resolved by adding a fill = TRUE in the `rbind` function that is within the `load_from_url` function that `load_rosters` calls.

**Comment by tanho63** [comment]
Can you provide your nflverse_sitrep() here please?

**Comment by shirondru** [comment]
This seems to have resolved itself after I updated R and re-installed nflreadr, while preparing the PR for the other issue. Apologies for the confusion.
