### ISSUE TITLE
load_schedule()

### ISSUE THREAD

**Issue by grayhawk40** [nflverse/nflreadr#139]
when I use nflreadr::load_schedules(seasons = TRUE)  it is giving me a NULL data frame.

**Output:**
nflreadr::load_schedules(seasons = TRUE)
── nflverse games and schedules ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# A tibble: 0 × 0

**sessionInfo**
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

**Comment by tanho63** [comment]
Try `nflreadr::.clear_cache()`
