### ISSUE TITLE
`get_current_week()` outputs different weeks for `use_date` = TRUE/FALSE on some weekdays

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflreadr#146]
https://github.com/nflverse/nflreadr/blob/1b5c004f1938be8c5ca310f48eafee2e341566e4/tests/testthat/test-utils_date.R#L5-L8

The above test fails after Monday Night Football because use_date = FALSE updates to the next week instantly after the game is finished whereas use_date = TRUE updates to the next week on Thursday (maybe Friday?).

**Comment by mrcaseb** [comment]
Failing test is fixed in #148 but we should probably update the function docs with an explanation for that behaviour

**Comment by tanho63** [comment]
time to create a "feature not a bug" label
