### ISSUE TITLE
Export `cache_clear()` without the dot prefix so that it's more obvious to users

### ISSUE THREAD

**Issue by tanho63** [nflverse/nflreadr#154]

**Comment by mrcaseb** [comment]
Probably worth to think about renaming it to something like `nflreadr_clear_cache()` to prevent namespace collisions in possible future packages. 

I did that in nflplotR.

**Comment by tanho63** [comment]
I've kind of circled back the other way on naming - `nflreadr::clear_cache()` should be sufficient?

**Comment by mrcaseb** [comment]
Definitely sufficient. I was just thinking of namespace collisions in nflverse packages. Currently it's only nflplotR (which is resolved) so I am fine.

**Comment by tanho63** [comment]
Right. I'm somewhat against `library(nflverse)` but that would be where it's most noticeable
