### ISSUE TITLE
change the desc of `special`?

### ISSUE THREAD

**Issue by ak47twq** [nflverse/nflreadr#163]
![image](https://user-images.githubusercontent.com/72854702/194061742-47a567c8-19ce-4500-b7dc-00902e55654c.png)
maybe change the description, state what seb said on discord.
Special is defined as 1 if play_type is one of "extra_point","field_goal","kickoff","punt"
Otherwise it’s 0.
rightnow the description seems to be a little bit confusing

**Comment by tanho63** [comment]
Happy to take a PR on this if you want to, I wrote a guide here: https://github.com/nflverse/nflreadr/tree/main/data-raw#updating-a-dictionary
