### ISSUE TITLE
`nflreadr::clean_homeaway()` overwrites location data

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflreadr#169]
https://github.com/nflverse/nflreadr/blob/53eca51f88d59229b0dbf9910e3a3a59fed220ea/R/utils_name_cleaning.R#L148
https://github.com/nflverse/nflreadr/blob/53eca51f88d59229b0dbf9910e3a3a59fed220ea/R/utils_name_cleaning.R#L154

These lines overwrite location data which means neutral site game information gets lost

**Comment by mrcaseb** [comment]
https://github.com/nflverse/nflreadr/blob/53eca51f88d59229b0dbf9910e3a3a59fed220ea/R/utils_name_cleaning.R#L160

I am also not 100% sure we want to drop the "nflverse_data" class here

**Comment by tanho63** [comment]
Agreed all counts. Probably should preserve attributes of original and reapply them tbh
