### ISSUE TITLE
[BUG] <title>Team fields not updated for recently traded players

### ISSUE THREAD

**Issue by MysteryPollster** [nflverse/nflreadr#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

1.3.1

### Describe the bug

When using the load_players() function, the fields team_abbr, current_team_id and jersey_number are not updated for recently traded players. For example, Nyheim Hines shows a playing for Colts, Chase Edmonds for Dolphins, etc. 

### Reprex

```r
players <- load_players()
```

### Expected Behavior

Code runs as expected - no problems with code

### nflverse_sitrep

```r
── System Info ──────────────────────────────────────────────────────────────────────────────────────
• R version 4.2.1 (2022-06-23)   • Running under: macOS Ventura 13.0
── nflverse Packages ────────────────────────────────────────────────────────────────────────────────
• nflreadr (1.3.1)  • nflseedR (1.1.0)  • nflplotR (1.1.0)  
• nflfastR (4.5.0)  • nfl4th   (1.0.2)  • nflverse (1.0.2)  
── nflverse Options ─────────────────────────────────────────────────────────────────────────────────
No options set for nflreadr, nflfastR, nflseedR, nfl4th, nflplotR, and nflverse
── nflverse Dependencies ────────────────────────────────────────────────────────────────────────────
ℹ The package `timechange` is required in your dependencies.
```

**Comment by tanho63** [comment]
Investigated this. Players get updated once a month at the moment on Nov 1st so I think it might have just missed the trade deadline. Manually triggered a re-run and hopefully should update shortly.

**Comment by mrcaseb** [comment]
Update confirmed
``` r
nflreadr::load_players() |> 
  dplyr::filter(gsis_id %in% c("00-0034681", "00-0034367")) |> 
  dplyr::select(status, display_name, team_abbr)
#> ── nflverse players ────────────────────────────────────────────────────────────
#> ℹ Data updated: 2022-11-16 01:36:58 CET
#> # A tibble: 2 × 3
#>   status display_name  team_abbr
#>   <chr>  <chr>         <chr>    
#> 1 ACT    Chase Edmonds DEN      
#> 2 ACT    Nyheim Hines  BUF
```
