### ISSUE TITLE
[BUG] load_injuries stopped working in week 13

### ISSUE THREAD

**Issue by ohri** [nflverse/nflreadr#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

1.3.1.5

### Describe the bug

load_injuries is unhappy as of beginning of week 13. There was data available for the thursday game, but the report status (questionable, out, etc.) wasn't filled in. Running it again Saturday morning, the same 25 rows were available, nothing for the rest of the games and no report status. I tried updating my nflfastr and nflreadr. 

In week 14, this returns an empty data frame. 

### Reprex

```r
nflreadr::.clear_cache()
nflreadr::load_injuries() %>% filter(week==14)
```

### Expected Behavior

Every week before 13, this gave Thursday game data (including report_status) if run on Thur or Fri, and status for all the games if run on Saturday or Sunday. 

### nflverse_sitrep

```r
ℹ You've asked for the packages nflseedR and nflverse which are not installed. 
They are skipped.
── System Info ────────────────────────────────────────────────────────────────────────────
• R version 4.2.1 (2022-06-23)   • Running under: macOS Ventura 13.0.1
── nflverse Packages ──────────────────────────────────────────────────────────────────────
• nflreadr (1.3.1.05)    • nfl4th   (1.0.2.9001)    
• nflfastR (4.5.0.9001)  • nflplotR (1.1.0)         
── nflverse Options ───────────────────────────────────────────────────────────────────────
No options set for nflreadr, nflfastR, nfl4th, and nflplotR
── nflverse Dependencies ──────────────────────────────────────────────────────────────────
• askpass     (1.1)     • httr       (1.4.4)    • progressr    (0.11.0)   
• cachem      (1.0.6)   • isoband    (0.2.5)    • purrr        (0.3.4)    
• cli         (3.4.0)   • janitor    (2.1.0)    • R6           (2.5.1)    
• codetools   (0.2-18)  • jsonlite   (1.8.0)    • rappdirs     (0.3.3)    
• colorspace  (2.0-3)   • labeling   (0.4.2)    • RColorBrewer (1.1-3)    
• cpp11       (0.4.2)   • lattice    (0.20-45)  • Rcpp         (1.0.9)    
• curl        (4.3.2)   • lifecycle  (1.0.2)    • rlang        (1.0.5)    
• data.table  (1.14.2)  • listenv    (0.8.0)    • scales       (1.2.1)    
• digest      (0.6.29)  • lubridate  (1.8.0)    • snakecase    (0.11.0)   
• dplyr       (1.0.10)  • magick     (2.7.3)    • stringi      (1.7.8)    
• ellipsis    (0.3.2)   • magrittr   (2.0.3)    • stringr      (1.4.1)    
• fansi       (1.0.3)   • MASS       (7.3-57)   • sys          (3.4)      
• farver      (2.1.1)   • Matrix     (1.4-1)    • tibble       (3.1.8)    
• fastmap     (1.1.0)   • memoise    (2.0.1)    • tidyr        (1.2.1)    
• fastrmodels (1.0.2)   • mgcv       (1.8-40)   • tidyselect   (1.1.2)    
• furrr       (0.3.1)   • mime       (0.12)     • timechange   (0.1.1)    
• future      (1.28.0)  • munsell    (0.5.0)    • utf8         (1.2.2)    
• generics    (0.1.3)   • nlme       (3.1-157)  • vctrs        (0.4.1)    
• ggplot2     (3.3.6)   • openssl    (2.0.2)    • viridisLite  (0.4.1)    
• globals     (0.16.1)  • parallelly (1.32.1)   • withr        (2.5.0)    
• glue        (1.6.2)   • pillar     (1.8.1)    • xgboost      (1.6.0.1)  
• gtable      (0.3.1)   • pkgconfig  (2.0.3)
```

**Comment by tanho63** [comment]
Thanks for the report! It looks like the nflverse-rosters repo actions got stopped for some reason, I've just restarted them and they should be updating again tomorrow.

**Comment by ohri** [comment]
Thanks for looking into that. Things started moving again, but I think it might have broken again? Not sure if it's the same problem or not.

Running it Friday morning, there were 14 rows in the data, all with report_status filled in. Running it Saturday morning, there are 277 rows, but the report_status is empty for all but the 14 that were filled in before.
