### ISSUE TITLE
[BUG] 2015 Roster Weeks Numbered Out of Order

### ISSUE THREAD

**Issue by mcarman8** [nflverse/nflreadr#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

nflreadr 1.3.2

### Describe the bug

The number for weeks is wrong in load_rosters_weekly() for 2015, it is ordered by alphabetical and not numeric.
Weeks lined up as:

1. 1
2. 10
3. 11
4. 12
5. 13
6. 14
7. 15
8. 16
9. 17
10. 2
11. 3
12. 4
13. 5
14. 6
15. 7
16. 8
17. 9

### Reprex

```r
library(nflreadr)
library(dplyr)

weekly_rosters <- load_rosters_weekly(seasons = 2015)

jamaal_charles <- weekly_rosters %>% dplyr::filter(full_name == "Jamaal Charles" & status == "Active")

print(jamaal_charles$week)
```

### Expected Behavior

Expected output is
[1] 1 2 3 4 5

Current output is 
[1] 1 10 11 12 13

Expected output is verified from [pro-football reference](https://www.pro-football-reference.com/players/C/CharJa00/gamelog/2015/) where Jamaal Charles was only active weeks 1-5

### nflverse_sitrep

```r
function (pkg = c("nflreadr", "nflfastR", "nflseedR", "nfl4th", 
    "nflplotR", "nflverse"), recursive = TRUE, redact_path = TRUE) 
{
    .sitrep(pkg = pkg, recursive = recursive, header = "nflverse ", 
        redact_path = redact_path)
}
<bytecode: 0x000002328408d578>
<environment: namespace:nflreadr>
```

### Additional context

It does not seem to affect the load_pbp function, as that is how I uncovered the bug, when players who generated stats in week 2 were not listed as active in load_weekly_rosters. I did not try with other functions in nflreadr/nflverse ecosystem.

**Comment by john-b-edwards** [comment]
This has been resolved:

```r
library(nflreadr)
library(dplyr)
#> Warning: package 'dplyr' was built under R version 4.2.2
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

weekly_rosters <- load_rosters_weekly(seasons = 2015)

jamaal_charles <- weekly_rosters %>% dplyr::filter(full_name == "Jamaal Charles" & status == "Active")

print(jamaal_charles$week)
#> [1] 1 2 3 4 5
```
