### ISSUE TITLE
hi, the sum of yards are not as same as pro-football-reference.com

### ISSUE THREAD

**Issue by ak47twq** [nflverse/nflreadr#183]
```
offense<-load_player_stats(seasons = TRUE)
offense_p<-offense%>%
  filter(season>=2000&season<=2009)%>%
  filter(season_type=="REG")
top<-offense_p%>%
  group_by(player_display_name,position)%>%
  summarise(rush=sum(rushing_yards),rec=sum(receiving_yards),yscm=rush+rec)
```
what i got is like this:
![image](https://user-images.githubusercontent.com/72854702/221411262-294ba794-2609-4a43-b52f-a52cefa91d62.png)

form `load_player_stats`, `LaDainian Tomlinson` had `16442` Yards from Scrimmage: Receiving and Rushing Yards

but at pro-football-reference.com, `LaDainian Tomlinson` had `16445` Yards from Scrimmage: Receiving and Rushing Yards
![image](https://user-images.githubusercontent.com/72854702/221411355-30bf9db5-4c08-442b-943a-7fe0c7a86e0b.png)

`Edgerrin James` and `Tiki Barber` does not match with pro-football-reference.com too.

Any ideas why this mismatch happened？

Thanks.

**Comment by ak47twq** [comment]
![image](https://user-images.githubusercontent.com/72854702/221411771-ba983594-c772-465d-9642-390134f50542.png)

**Comment by ak47twq** [comment]
![image](https://user-images.githubusercontent.com/72854702/221411814-6950d257-2f00-4837-a961-2519893410d9.png)

**Comment by mrcaseb** [comment]
Data from the 1999-2001 seasons is not as reliable as newer seasons. It's most likely related to differing stats provided in the underlying data. So we can't work around this unless we break it down to the relevant plays.
