### ISSUE TITLE
Most recent season is an idiot

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflreadr#186]
https://github.com/nflverse/nflreadr/blob/2c0c75522f4e2f08fa1c99ed1e33623eea5d3532/R/utils_date.R#L19

This line returns FALSE if the current day is < 15 even if month is > 3!

**Comment by tanho63** [comment]
_i don't even wanna look at the git blame here_

**Comment by tanho63** [comment]
_cause it was definitely me all along_

**Comment by mrcaseb** [comment]
I am pretty sure it was me which is why I called it idiotic
