### ISSUE TITLE
`nflverse_game_id` rejects abbreviations too aggressive and outputs bad error message

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflreadr#190]
``` r
away_teams <- c("LA", "LA", "LAR", "SD")
home_teams <- c("KC", "KC", "KC", "KC")
nflreadr::nflverse_game_id(2022, 2, away_teams, home_teams)
#> Error in `nflreadr::nflverse_game_id()`:
#> ! "LA", "LA", "LAR", and "SD" is not a valid `away` abbreviation.
#> Backtrace:
#>     ▆
#>  1. └─nflreadr::nflverse_game_id(2022, 2, away_teams, home_teams)
#>  2.   └─cli::cli_abort("{.val {away}} is not a valid {.arg away} abbreviation.")
#>  3.     └─rlang::abort(...)
```

`SD` is a valid (but old) team abbreviation and the error messages prints the complete input vector instead of the rejected abbreviation

**Comment by tanho63** [comment]
>  error messages prints the complete input vector instead of the rejected abbreviation
agree this is good fix
> SD is a valid (but old) team abbreviation
hm, would you prefer to check against a dataframe of every valid team + season combo?

**Comment by mrcaseb** [comment]
I think I prefer running keeping all team names listed in `nflreadr::team_abbr_mapping_norelocate`
