### ISSUE TITLE
Tank Dell Name Mapping issue.

### ISSUE THREAD

**Issue by TheMathNinja** [nflverse/nflreadr#194]
I think `nflreadr::clean_player_names()` should be mapping "Nathaniel Dell" to "Tank Dell".

Other updates:
Decobie Durant -> Cobie Durant
Riq Woolen -> Tariq Woolen
JuJu Brents -> Julius Brents
Dax Hill -> Daxton Hill

As a bonus, this isn't in the documentation yet for `nflreadr::player_name_mapping()` but listing the standard name this function converts to would be helpful (NFL.com seems reasonable?). That's what I'm using here.

**Comment by tanho63** [comment]
also should update `nflreadr::clean_player_names()` docs so that it suggests issues go in nflverse/nflreadr - ffscrapr now wraps this

**Comment by mrcaseb** [comment]
in my opinion, we should run something like this over all seasons to create a broader player name db

```r
r <- nflapi::nflapi_roster(2022) |> nflapi::nflapi_roster_parse()

mapping <- r |> 
  dplyr::transmute(
    nfl_name = player_display_name,
    uncommon = paste(player_first_name, player_last_name)
  ) |> 
  dplyr::filter(nfl_name != uncommon)
```

This outputs a name mapping for {uncommon first name, last name} combos to display names.

**Comment by tanho63** [comment]
I think I disagree in that I’d rather have a very small name database that gets updated when required - we might otherwise end up with too many name substitutions for more “common” names, eg we don’t want every John Smith to be renamed Juju Smith Schuster

**Comment by mrcaseb** [comment]
This argument is true for every name in the current list but I am fine with keeping the list small. Just need someone to keep it updated when new issues are opened
