### ISSUE TITLE
Bad records in weekly rosters table

### ISSUE THREAD

**Issue by tashapiro** [nflverse/nflreadr#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

current

### Describe the bug

Hi! 

First of all - thank for putting together this wonderful package. 

Just a heads up, I was working with nflreadr load_rosters_weekly and came across some glitchy records. In some instances, the wrong player info is associated to a gsis_id. Screenshot below with an example:

<img width="401" alt="Screenshot 2023-08-17 at 10 09 40 AM" src="https://github.com/nflverse/nflreadr/assets/44143974/b986cbb5-fae5-4efd-b536-6ebf42824dc4">

Code to reproduce the example:
```library(nflfastR)
library(tidyverse)

weekly<-nflreadr::load_rosters_weekly(TRUE)

weekly|>
  filter(gsis_id == '00-0024333')|>
  group_by(gsis_id, full_name)|>
  summarise(records = n())|>
  arrange(-records)
```

There are roughly 190 records that have more than one last name associated to the same ID. It's not totally full proof, in some instances it's legitimate (there are hyphenations, or rarely, a name change like Deonte Harris to Deonte Harty). Here is the code I used for the dupe check:

```group_by(gsis_id)|>
  summarise(count = n_distinct(toupper(last_name)))|>
  filter(count>1)
```

Appreciate your help looking into this!

### Reprex

```r
Provided in description above.
```

### Expected Behavior

Correct player information for reach gsis_id

### nflverse_sitrep

```r
N/A
```

### Screenshots

```markdown
Added in description
```

**Comment by tanho63** [comment]
Thanks! Will track this in nflverse/nflverse-rosters#73
