### ISSUE TITLE
sitrep functions could check to see if there is a newer version of specified packages on CRAN + r-universe

### ISSUE THREAD

**Issue by tanho63** [nflverse/nflreadr#206]
It would be useful if the sitrep functions could automatically tell the user that the specified packages are up to date with latest devel and latest cran package versions, e.g.

```r
> nflreadr::nflverse_sitrep()
── System Info ─────────────────────────────────────────────
• R version 4.3.0 (2023-04-21) • Running under: Ubuntu 20.04.6 LTS
── Package Status ──────────────────────────────────────────
• nflreadr Installed: 1.3.2.01,   CRAN: 1.3.2, devel: 1.3.2.09 [!]
• nflfastR Installed: 4.5.1.9004, CRAN: 4.5.1, devel: 4.5.1.9004

```

**Comment by mrcaseb** [comment]
That's what I wrote nflverse_update for https://nflverse.nflverse.com/reference/nflverse_update.html

**Comment by tanho63** [comment]
Ope, I totally didn't know you did that! Looking it over now.
