### ISSUE TITLE
Fast_scraper_roster is missing a bunch of kickers from past 8 years

### ISSUE THREAD

**Issue by Jeffery-777** [nflverse/nflreadr#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

1.0.3

### Describe the bug

`player.names <- fast_scraper_roster(1999:2023)`

Ran this and noticed the most recent kicker is from 2018 and there's only one. The next recent are all from 2015. Need this for my WAR code to bring the kickers along.

thanks much!

### Reprex

```r
`player.names <- fast_scraper_roster(1999:2023)`
```

### Expected Behavior

Hoping to see kickers for 2023 

### nflverse_sitrep

```r
NA
```

**Comment by john-b-edwards** [comment]
Post 2016, we've been using a different source to pull rosters that had more information and detail. Unfortunately, the way that roster source tagged `position` for kickers was inconsistent with how `position` was tagged for our pre-2016 roster source (essentially, pre-2016, `position` would be `K` and `depth_chart_position` would be `NA`, 2016-on, `position` would be `SPEC` for "Specialist" and `depth_chart_position` would be `K`). We've resolved that inconsistency with the newest roster rebuild:

```r
nflreadr::load_rosters(2007:2023) |>
    dplyr::filter(last_name == "Folk") |>
    dplyr::select(first_name, last_name, position, team, season)
#> ── nflverse roster data ────────────────────────────────────────────────────────
#> ℹ Data updated: 2023-09-12 18:19:21 PDT
#> # A tibble: 16 × 5
#>    first_name last_name position team  season
#>    <chr>      <chr>     <chr>    <chr>  <int>
#>  1 Nick       Folk      K        DAL     2007
#>  2 Nick       Folk      K        DAL     2008
#>  3 Nick       Folk      K        DAL     2009
#>  4 Nick       Folk      K        NYJ     2010
#>  5 Nick       Folk      K        NYJ     2011
#>  6 Nick       Folk      K        NYJ     2012
#>  7 Nick       Folk      K        NYJ     2013
#>  8 Nick       Folk      K        NYJ     2014
#>  9 Nick       Folk      K        NYJ     2015
#> 10 Nick       Folk      K        NYJ     2016
#> 11 Nick       Folk      K        TB      2017
#> 12 Nick       Folk      K        NE      2019
#> 13 Nick       Folk      K        NE      2020
#> 14 Nick       Folk      K        NE      2021
#> 15 Nick       Folk      K        NE      2022
#> 16 Nick       Folk      K        TEN     2023
```

**Comment by Jeffery-777** [comment]
Thank much John! I'll check it out.
