### ISSUE TITLE
More flexible infrastructure with something like `load_urls()`?

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflreadr#223]
Thinking about a function that loads a small file in which we maintain the actual download urls so we can change them without having to change nflreadr code.

**Comment by tanho63** [comment]
Hmm, thinking about this on second pass and I think I’d want to have the documentation and function args the way we have it now?

**Comment by mrcaseb** [comment]
I think I wasn't clear enough. I was thinking about an internal function that returns the download url for the loading function. Nothing user facing. 
So we would run something like `load_url("pbp")` and it returns `"https://github.com/nflverse/nflverse-data/releases/download/pbp/play_by_play_"` which we use in load_pbp

It would allow us to redirect loaders without having to change and/or release nflreadr.

**Comment by tanho63** [comment]
> It would allow us to redirect loaders without having to change and/or release nflreadr.

I like the version-controlled aspect of the current setup and hesitate to get rid of that but I think a csv of the URL fragments might be suitable if you want something programmatic

**Comment by mrcaseb** [comment]
Yeah we could version control the csv inside the nflreadr repo. It's not a strong opinion. Just thinking about more flexibility, especially given the recent problems with CRAN incoming checks. Lower number of releases means less pain for us.

**Comment by tanho63** [comment]
Closing as not-planned
