### ISSUE TITLE
Third down conversion via defensive penalty

### ISSUE THREAD

**Issue by arjunmenon10** [nflverse/nflreadr#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

The third_down_converted column to be a 1 if a third down was converted via defensive penalty (pass interference, holding, illegal contact, etc). I've tried doing some case_when statements to change it, but I'm not 100% sure if I'm capturing all the edge cases.

### Describe alternatives you've considered

pbp <- pbp |> 
  mutate(
    yards_gained = case_when(
      yards_gained == 0 & penalty_team != posteam & penalty_yards > 0 ~ penalty_yards,
      TRUE ~ yards_gained
    )
  )

is the code I wrote to change yards_gained to whatever the penalty yards were, then can do a basic statement saying 1st down converted if yards_gained > ydstogo

**Comment by guga31bb** [comment]
This behavior is kind of dumb but actually expected/intended behavior because it comes from official NFL stat IDs and thus replicates official NFL stats. Let's take BAL-CLE since there were a lot of penalties that game. [Officially](https://www.espn.com/nfl/matchup/_/gameId/401547531), the Ravens converted 2 of 8 third downs:

![image](https://github.com/nflverse/nflreadr/assets/1425357/44930044-c672-407f-a981-46fe460efa2c).

We can reproduce this in nflreadr by looking at non-penalty plays:

```
> nflreadr::load_pbp(2023) |> filter(week == 10, posteam == "BAL", down == 3) |> filter(rush == 1 | pass == 1, penalty == 0) |> select(desc, first_down)
── nflverse play by play data ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Data updated: 2023-11-13 04:04:29 EST
# A tibble: 8 × 2
  desc                                                                                                   first_down
  <chr>                                                                                                       <dbl>
1 (3:38) (Shotgun) 8-L.Jackson pass incomplete deep right to 34-K.Mitchell.                                       0
2 (15:00) (Shotgun) 8-L.Jackson pass incomplete deep middle to 15-N.Agholor.                                      0
3 (4:43) (Shotgun) 8-L.Jackson pass incomplete deep right to 4-Z.Flowers.                                         0
4 (3:12) (Shotgun) 8-L.Jackson sacked at CLE 37 for -5 yards (sack split by 99-Z.Smith and 0-G.Newsome).          0
5 (12:37) (Shotgun) 8-L.Jackson pass short right to 3-O.Beckham for 40 yards, TOUCHDOWN.                          1
6 (:35) (Shotgun) 8-L.Jackson sacked at BAL 45 for -9 yards (95-M.Garrett).                                       0
7 (7:37) (Shotgun) 8-L.Jackson pass short right to 4-Z.Flowers to BAL 38 for 11 yards (0-G.Newsome).              1
8 (5:51) (Shotgun) 8-L.Jackson scrambles left end to BAL 41 for 7 yards (99-Z.Smith).                             0 
```

The Ravens also converted three third downs via penalty: 


```
> nflreadr::load_pbp(2023) |> filter(week == 10, posteam == "BAL", down == 3) |> filter(rush == 1 | pass == 1, penalty == 1) |> select(desc, first_down)
── nflverse play by play data ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Data updated: 2023-11-13 04:04:29 EST
# A tibble: 3 × 2
  desc                                                                                                                                                        first_down
  <chr>                                                                                                                                                            <dbl>
1 "(6:07) (Shotgun) 8-L.Jackson pass short right to 35-G.Edwards to BAL 25 for no gain (1-J.Thornhill).\r\nPENALTY on CLE-21-D.Ward, Illegal Contact, 5 yard…          1
2 "(14:00) (Shotgun) 8-L.Jackson pass incomplete short right [95-M.Garrett].\r\nPENALTY on CLE-0-G.Newsome, Defensive Holding, 5 yards, enforced at CLE 11 -…          1
3 "(12:21) (Shotgun) 8-L.Jackson pass deep right intended for 34-K.Mitchell INTERCEPTED by 26-R.McLeod at CLE -8. Touchback. BAL-79-R.Stanley was injured du…          1
```

But officially, these count as neither a third down attempt nor conversion. Using the [NFL language](https://www.nflgsis.com/gsis/documentation/Partners/StatIDs.html), these are assigned stat ID 5, but not 6 or 7.

I would suggest using the `first_down` column that we create because this accounts for penalties.
