### ISSUE TITLE
add/document dictionary improvement for load_rosters()$status

### ISSUE THREAD

**Issue by tanho63** [nflverse/nflreadr#232]
c/o @john-b-edwards in discord

> 
> status_description_abbr is an abbreviated representation of the status column. it's fairly trivial to see what each acronym refers to using both columns:
> ```
> nflreadr::load_rosters(2022) |>
>     dplyr::group_by(status_description_abbr, status) |>
>     dplyr::summarise(.groups="drop") |>
>     print(n=21)
> #> # A tibble: 21 × 2
> #>    status_description_abbr status         
> #>    <chr>                   <chr>          
> #>  1 A01                     Active         
> #>  2 E02                     Ex/Comm. Perm. 
> #>  3 P01                     Practice Squad 
> #>  4 P02                     Prac Sq.; Inj  
> #>  5 P03                     Int'l PSquad   
> #>  6 P06                     PS; Exc        
> #>  7 P07                     PS; Vet        
> #>  8 R01                     R/Injured      
> #>  9 R02                     R/Retired      
> #> 10 R03                     R/DNR          
> #> 11 R04                     R/PUP          
> #> 12 R05                     R/NFIN         
> #> 13 R06                     R/Left Squad   
> #> 14 R23                     Reserve/Future 
> #> 15 R27                     R/NFIL         
> #> 16 R30                     R/Com Sus-1 Yr 
> #> 17 R33                     R/Club Susp.   
> #> 18 R40                     R/Susp < 1Yr   
> #> 19 R47                     R/NFIN; DFR    
> #> 20 R48                     R/Injured; DFR 
> #> 21 W03                    Waivers/No Rec.
> ```

**Comment by mrcaseb** [comment]
Closing this as I have dropped the status abbr because it's just some sort of ID for status and status short description.
