### ISSUE TITLE
[FEATURE REQ] Add "Hollywood Brown" to clean_player_names() 

### ISSUE THREAD

**Issue by TheMathNinja** [nflverse/nflreadr#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

clean_player_names("Hollywood Brown") returns "Hollywood Brown" but should return "Marquise Brown".

### Describe the solution you'd like

Returns "Marquise Brown"

**Comment by tanho63** [comment]
do you want to make a PR for this? involves:
- update this file: https://github.com/nflverse/nflreadr/blob/main/data-raw/clean_player_names.csv 
- run this script https://github.com/nflverse/nflreadr/blob/main/data-raw/build_teamplayer_mappings.R 

See https://usethis.r-lib.org/articles/pr-functions.html for more details.

**Comment by TheMathNinja** [comment]
Ugh sorry taking care of a baby right now and can't quite follow the steps given the circumstance.

**Comment by tanho63** [comment]
Cool, feel free to come back to it when you can
