### ISSUE TITLE
Add `weekly` option to `load_player_stats()`

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflreadr#35]
This would load the summarized version of `nflfastR::calculate_player_stats(weekly = FALSE)` because especially `dakota` can't be summarized afterwards. 

Can't be implemented until https://github.com/nflverse/nflfastR-data/issues/56 isn't resolved

**Comment by tanho63** [comment]
Would prefer “summarize_by” - “week”, “season”, “all”? (For multi-year?)

**Comment by mrcaseb** [comment]
Season level summary would be precalculated in the nflfastR-data repo because it requires the Dakota model. 
I like `summarize_by` but since it's precalculated we can only do "week" and "season"

**Comment by mrcaseb** [comment]
Thought about this again and remembered why we only provide the weekly stats. 

`weekly = FALSE` summarizes the given pbp data by player id only. This means the user has to decide which data to put into the function for example to filter regular or postseason or to summarize multiple seasons. 
It doesn't make sense to provide precalculated data for all cases.

**Comment by tanho63** [comment]
Closing, since it seems like consensus is to only return weekly data and leave summarise to the user
