### ISSUE TITLE
load_teams has a mispelling in team_division

### ISSUE THREAD

**Issue by jthomasmock** [nflverse/nflreadr#46]
The column label for `nflreadr::load_teams()` for `team_division` is misspelled as `team_divison`.

``` r
nflreadr::load_teams() |>
  dplyr::select(team_divison) |> 
  names()
#> [1] "team_divison"
```

<sup>Created on 2021-09-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

```
packageVersion("nflreadr")
[1] ‘1.0.0.5’
```

**Comment by tanho63** [comment]
Not sure how this is generated in https://github.com/nflverse/nflfastR-data but hopefully is manual and I can just edit it there (@mrcaseb ?)

**Comment by mrcaseb** [comment]
Oh wow. That's my fault. It is created manually and can be modified in the nflfastR-data repo. We need to fix both csv and rds

**Comment by tanho63** [comment]
okey i got it

*Tan Ho*

**Comment by tanho63** [comment]
woops got eager in the autoclose. Should be fixed now
