### ISSUE TITLE
Faile to download headshot_url

### ISSUE THREAD

**Issue by brunomioto** [nflverse/nflreadr#54]
**Describe the bug**

```r
Error in download_url(path) : 
  Failed to download https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/4036651.png (HTTP 415)
```
This headshot_url is from Kindle Vildor (DB) from Chicago Bears

**Comment by tanho63** [comment]
@brunomioto I believe Seb fixed this in his last data update, closing - please reopen if there are problems!
