### ISSUE TITLE
old_game_id not matching with NextGenStats gameId

### ISSUE THREAD

**Issue by ajreinhard** [nflverse/nflreadr#55]
I started scraping some of the NextGenStats Game Center data following Week 1 and my code to refresh for Weeks 2-3 does not appear to join correctly because the `old_game_id` for nflreadr doesn't match what I'm getting from NGS. I'm not sure if I should share the code I'm using to access the NextGenStats endpoint on here (because I need to use a cookie and I don't know if I should be sharing that kind of thing?), but I can privately if that helps.

Here is what I found in nflreadr versus this NGS endpoint `https://nextgenstats.nfl.com/api/league/schedule?season=2021` on [this page](https://nextgenstats.nfl.com/stats/game-center)

``` r
library(tidyverse)
library(nflreadr)

load_schedules(2021) %>% 
  filter(old_game_id == 2021092602) %>% 
  select(game_id, old_game_id)
#> # A tibble: 1 x 2
#>   game_id        old_game_id
#>   <chr>          <chr>      
#> 1 2021_03_LAC_KC 2021092602
```
VS
![image](https://user-images.githubusercontent.com/30268300/134960416-255c7b23-2b63-4a1e-abd7-00b0ead1c4d6.png)

And here are the differences I have for Week 3's games:
![image](https://user-images.githubusercontent.com/30268300/134960770-1b19fbb7-c3cc-4db2-bde1-b1c942768cac.png)

Let me know if I can provide additional code or context. Thanks!

**Comment by mrcaseb** [comment]
Oh this is weird. Tagging @leesharpe because those IDs are coming from his games data

**Comment by leesharpe** [comment]
The games data has been updated with the correct IDs.

**Comment by ajreinhard** [comment]
I'm seeing this issue again, but only with half the games from Week 15 of 2021. The correct mapping for these nine games is listed below.

``` r
library(dplyr)
library(nflreadr)

true_old_game_id_teams <- load_participation(2016:2021) |> 
  filter(possession_team != '') |> 
  group_by(old_game_id) |> 
  summarise(
    team1 = sort(unique(possession_team))[1],
    team2 = sort(unique(possession_team))[2]
  ) |> 
  group_by(team1, team2) |> 
  mutate(matchup_number = row_number()) |> 
  ungroup()

current_mapping_old_game_id_teams <- load_schedules(2016:2021) |> 
  mutate(
    team1 = ifelse(home_team < away_team, home_team, away_team),
    team2 = ifelse(home_team < away_team, away_team, home_team)
  ) |> 
  select(game_id, old_game_id, team1, team2) |> 
  group_by(team1, team2) |> 
  mutate(matchup_number = row_number()) |> 
  ungroup()

anti_join(current_mapping_old_game_id_teams, true_old_game_id_teams) |> 
  left_join(true_old_game_id_teams, by = c('team1', 'team2', 'matchup_number'), suffix = c('_current', '_correct')) |> 
  select(contains('game_id'))
#> Joining, by = c("old_game_id", "team1", "team2", "matchup_number")
#> # A tibble: 9 × 3
#>   game_id         old_game_id_current old_game_id_correct
#>   <chr>           <chr>               <chr>              
#> 1 2021_15_CAR_BUF 2021121901          2021121909         
#> 2 2021_15_ARI_DET 2021121903          2021121901         
#> 3 2021_15_HOU_JAX 2021121905          2021121902         
#> 4 2021_15_NYJ_MIA 2021121906          2021121910         
#> 5 2021_15_DAL_NYG 2021121907          2021121903         
#> 6 2021_15_TEN_PIT 2021121909          2021121904         
#> 7 2021_15_CIN_DEN 2021121910          2021121905         
#> 8 2021_15_ATL_SF  2021121911          2021121906         
#> 9 2021_15_NO_TB   2021121913          2021121908
```

**Comment by tanho63** [comment]
Hmm. I wonder if we should be trying to reconstruct Lee's "new game ID" from season + week + home + away rather than using the numeric "old" IDs...

**Comment by mrcaseb** [comment]
> Hmm. I wonder if we should be trying to reconstruct Lee's "new game ID" from season + week + home + away rather than using the numeric "old" IDs...

I agree, we should try to implement the "season_week_away_home" ID in all of our data to be consistent. If anybody wants the other ID, it is easy to join Lee's games data. And if IDs are wrong in there he can fix it.
