### ISSUE TITLE
Duplicated entries in load_rosters() 2021

### ISSUE THREAD

**Issue by SCasanova** [nflverse/nflreadr#58]
**Describe the bug**
When loading 2021 rosters, a variation of headshot_url makes multiple rows per player/season combination

**Reprex**
``` r
library(magrittr)
nflreadr::load_rosters(2021) %>% 
  dplyr::filter(full_name == 'Joe Mixon') %>% 
  dplyr::pull(headshot_url)
#> [1] "https://static.www.nfl.com/image/private/f_auto,q_auto/league/a577vg2x4mz7eqo0ejsw"
#> [2] "https://static.www.nfl.com/image/private/f_auto,q_auto/league/pucb3gqsidpxzivdp9hd"
```

<sup>Created on 2021-10-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Expected behavior**
This in turn creates duplicates when merging so I was curious if it was intentional

**Session information**

```r
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6
```

**Comment by mrcaseb** [comment]
gdi stupid NFL. At least it's both the same player

**Comment by mrcaseb** [comment]
I have pushed an updated headshot gsis map in https://github.com/nflverse/nflfastR-roster/commit/18b576e020c6b49863bdb869e4dfacbda0de6206

The workflow is currently running so the data should be updated in about 10 minutes. 

I will close this but please reopen if there are still problems @SCasanova
