### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by Grayhawk34** [nflverse/nflreadr#72]
Hi,

Thanks for the package; a lot of work went into this and I appreciate it.  But, I consistently find missing data within each of the data assets.  For instance:

nflreadr::load_nextgen_stats(stat_type = "receiving",seasons = 2021)  %>% filter(player_display_name ==  "Allen Robinson")

will only show 5 entries for regular season games.....he's played in 9 games to-date.

nflreadr::load_ff_rankings(type ="week") won't have all the players.  In fact, the entire ATL defense is missing.  While other teams have their full rosters.

The rosters is not complete either nor is the injury list valid.  I've checked it with other injury lists.  I'd like to use it b/c it shows defensive players injuries where my other sources don't but the quality isn't there.

These are just small examples.  But I've found hundreds of examples.  

How is the data quality checked?  Is there anything we can do to remedy the inconsistencies?

**Comment by mrcaseb** [comment]
Let's start with the Allen Robinson NGS example. We load this data from the Next Gen Stats website which uses a minimum of 5 targets for receiving stats. 

Robinson had 4 targets in weeks 2, 7, and 8. And he had 3 targets in week 4.

**Comment by mrcaseb** [comment]
What does 
> The rosters is not complete
mean? Can you give an example of what's wrong in your opinion?

**Comment by tanho63** [comment]
On a broader note: the nflverse project is a collection of code and data repositories maintained by volunteers, some of which are automated scraping of public websites. If you would like to report a specific data bug, please open an issue in the correct repository. 

You can usually get an idea of which repo that is by printing out the source reference of the function (i.e. just typing `load_nextgen_stats` without parentheses). 

Closing this issue.
