### ISSUE TITLE
Load Snap Count Dictionary Out of Date. 

### ISSUE THREAD

**Issue by rogers1000** [nflverse/nflreadr#77]
`load_snap_count()` directionary is out of date. The PFR ID is listed as `PFR_id` when it should be `PFR_player_id`.

**Comment by tanho63** [comment]
Thanks for reporting! Do you maybe want to try fixing it for us? Approximate steps:
```r
# make your own local copy of nflreadr
usethis::create_from_github("nflverse/nflreadr")
# start a PR branch
usethis::pr_init(branch = "fix/snapcounts") # branch name can be whatever, this is a common syntax
```
- find the csv dictionary in question in /data-raw 
- fix the csv
- rerun contents of data-raw/build_data_dictionaries.R
- bump the version number at the very end of the DESCRIPTION file and add a line in NEWS.md
- git commit the changes
- run `usethis::pr_push()` and then make a PR

This is more or less what's described in https://usethis.r-lib.org/articles/pr-functions.html
