### ISSUE TITLE
add documentation about season-ending depth charts to load_depth_charts data dictionary

### ISSUE THREAD

**Issue by armstjc** [nflverse/nflreadr#78]
~~See title.~~
Washington Football Team Credited for a 2021 Week 19 game, despite missing the postseason

**Comment by mrcaseb** [comment]
> There appears to be a week 19 for all teams' depth charts from the NFL API. There is also a week 18 listed for the 2020 regular season (which was a 17 week season) and I presume other seasons as well. My best guess is that this is some sort of end-of-season depth chart -- i.e. John Bates is listed as TE1 for the WFT for Week 19, 2021 instead of Ricky Seals-Jones -- Seals-Jones was inactive for week 18 and Bates was on the field for 100% of snaps Week 18.
> 
> 
> 
> I think we should make a note of this in the `{nflreadr}` documentation but otherwise not change the code.

I don't have a reprex currently but checked Number of teams in week 19 for all seasons and it was a bit weird. 
- > 30 for the seasons 2001:2003
- 12 for the seasons 2004:2019
- 32 for 2020 and 2021
(or something close to that)

**Comment by john-b-edwards** [comment]
... also odd. I only checked 2020 and 2021

**Comment by john-b-edwards** [comment]
To be clear you're referencing week 18* for 2020 right?

**Comment by mrcaseb** [comment]
> To be clear you're referencing week 18* for 2020 right? @mrcaseb 
> 
> 

No I don't. That's the fun thing. I did week 19 because of laziness. Changed it afterwards to season_type == "REG" which removed 2021 completely of course but kept the higher numbers for the earlier seasons.

**Comment by john-b-edwards** [comment]
... okay, gonna revert my PR then until we figure out what's going on.

**Comment by john-b-edwards** [comment]
I only see 10 teams for 2020, and they're listed as postseason teams.

```r
nflreadr::load_depth_charts(2020) |>
    dplyr::filter(week == 19)
#> # A tibble: 733 x 13
#>    season  week team  season_type position depth_chart_pos~ formation depth_team
#>     <int> <int> <chr> <chr>       <chr>    <chr>            <chr>          <int>
#>  1   2020    19 BUF   POST        OLB      WLB              Defense            2
#>  2   2020    19 BUF   POST        CB       NCB              Defense            1
#>  3   2020    19 BUF   POST        SS       S                Defense            1
#>  4   2020    19 BUF   POST        FS       S                Defense            1
#>  5   2020    19 BUF   POST        WR       PR               Special ~          2
#>  6   2020    19 BUF   POST        WR       KOR              Special ~          2
#>  7   2020    19 BUF   POST        T        LT               Offense            1
#>  8   2020    19 BUF   POST        G        LG               Offense            2
#>  9   2020    19 BUF   POST        C        C                Offense            1
#> 10   2020    19 BUF   POST        G        RG               Offense            2
#> # ... with 723 more rows, and 5 more variables: jersey_number <int>,
#> #   full_name <chr>, first_name <chr>, last_name <chr>, gsis_id <chr>
nflreadr::load_depth_charts(2020) |>
    dplyr::filter(week == 19) |>
    dplyr::pull(team) |>
    unique()
#>  [1] "BUF" "CHI" "BAL" "TEN" "IND" "LA"  "NO"  "PIT" "SEA" "TB"  "WAS" "CLE"
```
Meanwhile week 18 for 2020 has 32 teams with `season_type = 'REG'`.

I think my original intuition was correct, such that:

* Weeks 1-17/18 represent the depth charts for each game of the regular season.
* Week 18/19 represents an end-of-season depth chart for all regular season teams
* Week 19/20 represents the depth charts for the teams in the first week of the postseason.

Can probably clarify this further in the data dict.

**Comment by mrcaseb** [comment]
I wrote some code to look at this and I think its a bit inconsistent

- week 18 is missing for <2006
- postseason is missing for 2005
- SB is week 22 for 2004, 2006, 2014
- week 20 mostly > week 19

``` r
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)

df <- nflreadr::load_depth_charts(TRUE)

df |> 
  group_by(season, week, team) |> 
  summarise() |> 
  ungroup() |> 
  count(season, week) |> 
  mutate(alpha = ifelse(n == 32, 0.2, 1)) |> 
  ggplot(aes(x = season, y = week)) +
  geom_text(aes(label = n, alpha = alpha), size = 3) +
  scale_alpha_identity() +
  scale_y_continuous(breaks = scales::breaks_pretty(n = 10)) +
  theme_minimal()
#> `summarise()` has grouped output by 'season', 'week'. You can override using the `.groups` argument.
```

![](https://i.imgur.com/lKoVcHY.png)

<sup>Created on 2022-01-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by tanho63** [comment]
Oh lol whoops only read the PR

**Comment by tanho63** [comment]
Happy to take further edits as necessary

**Comment by john-b-edwards** [comment]
@mrcaseb great stuff, that really clarifies it. So my above comment holds true but only for 2007-2013, and 2015-2021. Seems like it may involve some data munging to get this into something resembling a consistent format?

My thought is:

* Drop end of season DC
* Re-order playoff DC such that WC week is week 1 instead of 19/20

Can get to this later today after work.

**Comment by mrcaseb** [comment]
I think we should discuss this in a separate nflfastr-roster issue as the code that creates this lives there. The SB week issue is based on the fact that the max regular season week in these seasons is 17 compared to 18 in the other seasons. I will open a new issue with the above code
